name: Lint Code

on:
  push:
     branches: [ master ]

jobs:
   lint:
      runs-on: ubuntu-20.04
      steps:
         - uses: actions/checkout@v2
         
         - name: install and lint with flake8
           run: | 
              pip install flake8
              cd /home/runner
              flake8
         

 
