name: Lint Code

on:
  push:
     branches: [ master ]

jobs:
   lint:
      runs-on: ubuntu-20.04
      steps:
         - uses: actions/checkout@v2
         
         - name: install flake8
           run: pip install flake8
         
         - name: lint
           run: flake8

 
